### ISSUE TITLE
Table display not scaling with column width on Chrome/Ubuntu Linux

### ISSUE THREAD

**Issue by jasonkholden** [manahl/dtale#13]
If you do a docker-compose up from 4b326896c2eff401410c6747e70771ebbc3f612d and then navigate to 127.0.0.1:8081 (dtale 3.6 pulling dated data from mongo), the formatting of the tabular data isn't scaling to column width.

![Screenshot from 2019-09-18 21-15-48](https://user-images.githubusercontent.com/6685128/65203672-af546900-da59-11e9-86d6-072203eab877.png)

**Comment by aschonfeld** [comment]
Yes, this is very tough problem to solve which is why I included the "Resize" button on the popup menu.  Can you try clicking that to see if it fixes it?

**Comment by aschonfeld** [comment]
Unfortunately I can't recreate this using any of the following:
- Chrome 77.0.3865.90 on linux
- Firefox 60.4.0esr on linux
- Chrome 76.0.3809.100 on Mac
- Chrome 67.0.3396.99 on Windows

**Comment by aschonfeld** [comment]
closed in v1.1.1
